[metadata]
name = electrology
version = 0.1.0
description = Small project to simulate the electromagnetic field in 1D and 2D.
long_description = file: README.md
long_description_content_type = text/markdown
author = Guillem Fernández ROdríguez
author_email = guillem.fernandez@uv.es
license = MIT
license_files = LICENSE
url = https://github.com/introspective-swallow/Electromagnetic-Wave-Simulation  # Replace with your repository
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
packages = find:
package_dir =
    = src
install_requires =
    tqdm
    matplotlib
    numpy
python_requires = >=3.7

[options.package_data]
* = *.txt, *.rst

[options.extras_require]
dev =
